//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UKareEntities : DbContext
    {
        public UKareEntities()
            : base("name=UKareEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Country> Countries { get; set; }
        public DbSet<MenuItem> MenuItems { get; set; }
        public DbSet<Message> Messages { get; set; }
        public DbSet<MessageType> MessageTypes { get; set; }
        public DbSet<Permission> Permissions { get; set; }
        public DbSet<PhotoGallery> PhotoGalleries { get; set; }
        public DbSet<RoleMenu> RoleMenus { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<SiteVisit> SiteVisits { get; set; }
        public DbSet<Speciality> Specialities { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<UserDocument> UserDocuments { get; set; }
        public DbSet<UserLogged> UserLoggeds { get; set; }
        public DbSet<VerificationToken> VerificationTokens { get; set; }
    }
}
