//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Messages = new HashSet<Message>();
            this.UserDocuments = new HashSet<UserDocument>();
            this.VerificationTokens = new HashSet<VerificationToken>();
            this.Specialities = new HashSet<Speciality>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Telephone { get; set; }
        public string MobileNumber { get; set; }
        public int CountryIdResd { get; set; }
        public int CountryIdQual { get; set; }
        public System.DateTime QualfiedDate { get; set; }
        public int JobLocation { get; set; }
        public string ExperienceIn1 { get; set; }
        public string ExperienceIn2 { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
        public Nullable<int> UpdatedByUserId { get; set; }
        public System.DateTime CreatedOnDatetime { get; set; }
        public System.DateTime UpdatedOnDatetime { get; set; }
        public bool IsActive { get; set; }
        public int RoleId { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Country Country1 { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<UserDocument> UserDocuments { get; set; }
        public virtual ICollection<VerificationToken> VerificationTokens { get; set; }
        public virtual ICollection<Speciality> Specialities { get; set; }
    }
}
